Http:
  IpAddr: ":7000"
Rpc:
  IpAddr: ":7001"
Nsq:
  RemoteAddr: "192.168.44.131:4150"
Redis:
  RemoteAddr: "192.168.44.131:6379"
  User: ""
  Pass: ""
  DB: 0
Elastic:
  HttpAddr: "http://192.168.44.131:9200"
  NodeAddr: "http://192.168.44.131:9300"
  Sniff: false