package utils

const (
	MsgServerSync     = "MsgServerSync"
	ApiPlayerLogin    = "APIPlayerLogin"
	ApiPlayerList     = "ApiPlayerList"
	ApiRoomCreate     = "ApiRoomCreate"
	ApiRoomList       = "ApiRoomList"
	ApiRoomJoin       = "ApiRoomJoin"
	ApiRoomLeave      = "ApiRoomLeave"
	ApiPlayerJoin     = "ApiPlayerJoin"
	ApiChatSend       = "ApiChatSend"
	MsgPlayerList     = "MsgPlayerList"
	MsgRoomList       = "MsgRoomList"
	MsgRoom           = "MsgRoom"
	ApiGameStart      = "ApiGameStart"
	MsgGameStart      = "MsgGameStart"
	MsgClientSync     = "MsgClientSync"
	TimePast          = "TimePast"
	WeaponShoot       = "WeaponShoot"
	MsgHp             = "MsgHp"
	MsgGameEnd        = "MsgGameEnd"
	MsgPlayerHallChat = "MsgPlayerHallChat"
	ApiGameKaPool     = "ApiGameKaPool"
)
const (
	Map1      = "Map1"
	Actor1    = "Actor1"
	Actor2    = "Actor2"
	Weapon1   = "Weapon1"
	Weapon2   = "Weapon2"
	Bullet1   = "Bullet1"
	Bullet2   = "Bullet2"
	Explosion = "Explosion"
	JoyStick  = "JoyStick"
	Shoot     = "Shoot"
)
